name 'artifact_packager'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures test1'
long_description 'Installs/Configures test1'
version '0.1.0'
